-- ========================================================
-- Supabase Schema for Screen Time App
-- Table: screen_time_stats
-- Description: Stores daily screen time usage per device and app,
--              configured with UNIQUE constraint for UPSERT deduplication.
-- ========================================================

-- 1. Create Table
CREATE TABLE IF NOT EXISTS public.screen_time_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT NOT NULL,
    usage_date DATE NOT NULL,
    package_name TEXT NOT NULL,
    app_name TEXT,
    total_time_in_foreground BIGINT DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- UNIQUE constraint required for ON CONFLICT (UPSERT) without duplicate records
    CONSTRAINT screen_time_stats_device_date_pkg_key UNIQUE (device_id, usage_date, package_name)
);

-- 2. Create Indexes for High Performance Queries
CREATE INDEX IF NOT EXISTS idx_screen_time_stats_device_id ON public.screen_time_stats(device_id);
CREATE INDEX IF NOT EXISTS idx_screen_time_stats_usage_date ON public.screen_time_stats(usage_date);
CREATE INDEX IF NOT EXISTS idx_screen_time_stats_package_name ON public.screen_time_stats(package_name);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.screen_time_stats ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for Anon & Authenticated Users
-- Allow insert / upsert for anon/authenticated clients
CREATE POLICY "Allow public insert and upsert"
ON public.screen_time_stats
FOR INSERT
WITH CHECK (true);

-- Allow select for anon/authenticated clients
CREATE POLICY "Allow public read"
ON public.screen_time_stats
FOR SELECT
USING (true);

-- Allow update for anon/authenticated clients
CREATE POLICY "Allow public update"
ON public.screen_time_stats
FOR UPDATE
USING (true)
WITH CHECK (true);

-- Grant privileges
GRANT ALL ON TABLE public.screen_time_stats TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
